#!/bin/sh

if grep -E 'Co-authored-by:.*([Cc]opilot|[Cc]laude)' $1 > /dev/null
then
    echo "never add a 'Co-authored-by'"
    exit 1
fi

GIT_DIR=`git rev-parse --absolute-git-dir`
HOOK_NAME=`basename $0`
LOCAL_HOOK="${GIT_DIR}/hooks/${HOOK_NAME}"

if [ -e $LOCAL_HOOK ]; then
  source $LOCAL_HOOK
fi
